#ifndef COMMON_H_
#define COMMON_H_

enum POWER_DELIVERY_REVISIONS {
    POWER_DELIVERY_REVISION_NONE = 60,
    POWER_DELIVERY_REVISION_2_0 = 61,
    POWER_DELIVERY_REVISION_3_0 = 62,
    POWER_DELIVERY_REVISION_3_1 = 63,
};

#endif
